program RsInterfaceDebug;

uses
  Forms,
  ufrmMain in 'ufrmMain.pas' {FrmMain},
  uGlobalDM in 'uGlobalDM.pas' {GlobalDM: TDataModule},
  uChildFrmMgr in 'uChildFrmMgr.pas',
  ufrmBasicDicDebug in '子窗口\基础字典接口测试\ufrmBasicDicDebug.pas' {FrmBasicDictDebug},
  ufrmAskLeaveDebug in '子窗口\请销假测试\ufrmAskLeaveDebug.pas' {FrmAskLeaveDebug},
  ufrmTrainmanMgrDebug in '子窗口\人员管理接口测试\ufrmTrainmanMgrDebug.pas' {FrmTrainmamMgrDebug},
  uLCBaseDict in '..\..\客户端\Source\接口\uLCBaseDict.pas',
  uLCDict_GuideGroup in '..\..\逻辑层BPL\Source\业务逻辑\新接口\字典接口\uLCDict_GuideGroup.pas',
  uLCDict_Jwd in '..\..\逻辑层BPL\Source\业务逻辑\新接口\字典接口\uLCDict_Jwd.pas',
  uLCDict_SignType in '..\..\逻辑层BPL\Source\业务逻辑\新接口\字典接口\uLCDict_SignType.pas',
  uLCDict_Station in '..\..\逻辑层BPL\Source\业务逻辑\新接口\字典接口\uLCDict_Station.pas',
  uLCDict_TrainJiaoLu in '..\..\逻辑层BPL\Source\业务逻辑\新接口\字典接口\uLCDict_TrainJiaoLu.pas',
  uLCDict_TrainmanJiaoLu in '..\..\逻辑层BPL\Source\业务逻辑\新接口\字典接口\uLCDict_TrainmanJiaoLu.pas',
  uLCDict_WorkPlan in '..\..\逻辑层BPL\Source\业务逻辑\新接口\字典接口\uLCDict_WorkPlan.pas',
  uLCDict_WorkShop in '..\..\逻辑层BPL\Source\业务逻辑\新接口\字典接口\uLCDict_WorkShop.pas',
  uLCAskLeave in '..\..\逻辑层BPL\Source\业务逻辑\新接口\请销假\uLCAskLeave.pas',
  uLCTrainmanMgr in '..\..\逻辑层BPL\Source\业务逻辑\新接口\人员管理\uLCTrainmanMgr.pas',
  uGuideGroup in '..\..\逻辑层BPL\Source\数据定义\uGuideGroup.pas',
  uGuideSign in '..\..\逻辑层BPL\Source\数据定义\uGuideSign.pas',
  uRoomSign in '..\..\逻辑层BPL\Source\数据定义\uRoomSign.pas',
  uRunEvent in '..\..\逻辑层BPL\Source\数据定义\uRunEvent.pas',
  uSaftyEnum in '..\..\逻辑层BPL\Source\数据定义\uSaftyEnum.pas',
  uSection in '..\..\逻辑层BPL\Source\数据定义\uSection.pas',
  uSickLeave in '..\..\逻辑层BPL\Source\数据定义\uSickLeave.pas',
  uStation in '..\..\逻辑层BPL\Source\数据定义\uStation.pas',
  uTrainJiaolu in '..\..\逻辑层BPL\Source\数据定义\uTrainJiaolu.pas',
  uTrainman in '..\..\逻辑层BPL\Source\数据定义\uTrainman.pas',
  uTrainPlan in '..\..\逻辑层BPL\Source\数据定义\uTrainPlan.pas',
  uWorkShop in '..\..\逻辑层BPL\Source\数据定义\uWorkShop.pas',
  uWriteCardSection in '..\..\逻辑层BPL\Source\数据定义\uWriteCardSection.pas',
  uXYRelation in '..\..\逻辑层BPL\Source\数据定义\uXYRelation.pas',
  uTrainmanJiaolu in '..\..\逻辑层BPL\Source\数据定义\uTrainmanJiaolu.pas',
  uDutyPlace in '..\..\逻辑层BPL\Source\数据定义\uDutyPlace.pas',
  uBaseWebInterface in '..\..\逻辑层BPL\Source\业务逻辑\接口基类\uBaseWebInterface.pas',
  uHttpCom in '..\..\逻辑层BPL\Source\功能单元\HTTP通信\uHttpCom.pas',
  ufrmLoading in '..\..\逻辑层BPL\Source\功能单元\HTTP通信\HTTP接口通信\ufrmLoading.pas' {frmLoading},
  uHttpCommEx in '..\..\逻辑层BPL\Source\功能单元\HTTP通信\HTTP接口通信\uHttpCommEx.pas',
  uHttpWebAPI in '..\..\逻辑层BPL\Source\功能单元\HTTP通信\HTTP接口通信\uHttpWebAPI.pas',
  uJWD in '..\..\逻辑层BPL\Source\数据定义\uJWD.pas',
  uLeaveListInfo in '..\..\逻辑层BPL\Source\数据定义\uLeaveListInfo.pas',
  ufrmEventDebug in '子窗口\事件接口\ufrmEventDebug.pas' {FrmEventDebug},
  ufrmWriteCardSectionDebug in '子窗口\写卡区段接口\ufrmWriteCardSectionDebug.pas' {FrmWriteCardSection},
  ufrmJiaoBanDebug in '子窗口\叫班接口\ufrmJiaoBanDebug.pas' {FrmJiaoBanDebug},
  uLCEvent in '..\..\逻辑层BPL\Source\业务逻辑\新接口\事件接口\uLCEvent.pas',
  uLCCallNotify in '..\..\逻辑层BPL\Source\业务逻辑\新接口\叫班\uLCCallNotify.pas',
  uCallNotify in '..\..\逻辑层BPL\Source\数据定义\uCallNotify.pas',
  uPubFun in '..\..\逻辑层BPL\Source\功能单元\公共函数\uPubFun.pas',
  uLCXYRelation in '..\..\逻辑层BPL\Source\业务逻辑\新接口\师徒关系\uLCXYRelation.pas',
  uLCTeamGuide in '..\..\逻辑层BPL\Source\业务逻辑\新接口\指导队\uLCTeamGuide.pas',
  uLCMealTicket in '..\..\逻辑层BPL\Source\业务逻辑\新接口\饭票\uLCMealTicket.pas',
  uLCDrink in '..\..\逻辑层BPL\Source\业务逻辑\新接口\测酒\uLCDrink.pas',
  uDrink in '..\..\逻辑层BPL\Source\数据定义\uDrink.pas',
  uLCGoodsMgr in '..\..\逻辑层BPL\Source\业务逻辑\新接口\物品管理\uLCGoodsMgr.pas',
  uLendingDefine in '..\..\逻辑层BPL\Source\数据定义\uLendingDefine.pas',
  uGoodsRange in '..\..\逻辑层BPL\Source\数据定义\uGoodsRange.pas',
  uDBLendingManage in '..\..\逻辑层BPL\Source\数据库操作\物品管理\uDBLendingManage.pas',
  uLLCommonFun in '..\..\逻辑层BPL\Source\通用函数\uLLCommonFun.pas',
  uLCDayPlan in '..\..\逻辑层BPL\Source\业务逻辑\新接口\机车计划\uLCDayPlan.pas',
  uTemplateDayPlan in '..\..\逻辑层BPL\Source\业务逻辑\新接口\机车计划\uTemplateDayPlan.pas',
  uFrmDrinkDebug in '子窗口\测酒接口\uFrmDrinkDebug.pas' {FrmDrinkDebug},
  ufrmDebugBase in '子窗口\ufrmDebugBase.pas' {FrmDebugBase},
  uFrmTeamGuideDebug in '子窗口\指导队\uFrmTeamGuideDebug.pas' {FrmTeamGuideDebug},
  ufrmXYRelationDebug in '子窗口\师徒关系\ufrmXYRelationDebug.pas' {FrmXYRelationDebug},
  ufrmGoodsMgrDebug in '子窗口\物品管理\ufrmGoodsMgrDebug.pas' {FrmGoodsMgrDebug},
  ufrmDayPlanDebug in '子窗口\机车计划\ufrmDayPlanDebug.pas' {FrmDayPlanDebug},
  uLCNameBoard in '..\..\逻辑层BPL\Source\业务逻辑\名牌管理\uLCNameBoard.pas',
  uLCWriteCardSectionV2 in '..\..\逻辑层BPL\Source\业务逻辑\新接口\写卡区段\uLCWriteCardSectionV2.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TGlobalDM, GlobalDM);
  GlobalDM.InitSystem();
  Application.CreateForm(TFrmMain, FrmMain);
  Application.Run;
end.
